[package]
name = "server_bin"
version = "0.1.0"
edition = "2021"
default-run = "server_api_all"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
server-core = {version = "*", path = "../../core", default-features = false}
server_api = {version = "*", path = "../../server_api", default-features = false}

rustgram = {workspace = true}
tokio = {workspace = true}
hyper = {workspace = true}
#tokio-util = {workspace = true}

[features]
default = ["mysql"]
mysql = ["server_api/mysql"]
sqlite = ["server_api/sqlite"]

send_mail = ["server_api/send_mail"]