[workspace]
members = [
    "sdk-common",
    "server_crates/core",
    "server_crates/server_all",
    "server_crates/server_api",
    "server_crates/server_api_common",
    "server_crates/server_api_file",
    "server_crates/helper/server_api_route_builder",
    "server_crates/helper/server_api_init",
    "server_crates/server_dashboard/server_dashboard_backend",
    #"server_crates/server_dashboard/client/server_dashboard_frontend",  #deactivate it after wasm update because we are using different features for sentc sdk
    #"server_crates/helper/server_migration"
]
