[workspace]
members = [
    "sdk-common",
    "server_crates/core",
    "server_crates/server_all",
    "server_crates/server_api",
    "server_crates/server_api_common",
    "server_crates/server_api_file",
    "server_crates/helper/server_api_route_builder",
    "server_crates/helper/server_api_init",
    "server_crates/helper/dummy_server",
    "server_crates/server_dashboard",
    #"server_crates/helper/server_migration"
]
