[workspace]
members = [
    # bin
    "server_crates/bin/server_bin",

    # bin for dev
    "server_crates/bin_dev/server_api_route_builder",
    #"server_crates/bin_dev/server_api_init",
    #"server_crates/bin_dev/dummy_server",
    #"server_crates/bin_dev/server_migration",

    # lib
    "sdk-common",
    "server_crates/server_api",
    "server_crates/server_api_common",
    "server_crates/worker/worker_manual"
]

[workspace.dependencies]
# server impl
hyper = { version = "0.14", features = ["full"] }
tokio = { version = "1", features = ["full"] }
tokio-util = "0.7.2"

rustgram = "0.1.8"

# dotenv vars
dotenv = "0.15.0"

# for caching trait
async-trait = "0.1.56"

rustgram-server-util = {version = "0.1.8", git= "https://gitlab.com/grammm/rustgram/rustgram-server-util.git", rev = "6cd0213aa8c89708e522a2be0c1ecd0f1aaa67a9", default-features = false, features = ["derive_macro"]}

#_______________________________________________________________________________________________________________________
# salt creation on server
# to get it from ssh: write this in your ~/.cargo/config.toml:
# [net]
# git-fetch-with-cli = true
sentc-crypto = {version = "0.1.0", git = "ssh://git@github.com/sentclose/sentc.git", rev="8c181a68aa8d82d1729d8895f06de4d888eb248a", default-features = false, features = ["rust", "server"]}

#_______________________________________________________________________________________________________________________
# json handling
serde_json = {version = "1.0.81", default-features = false, features = ["alloc"]}
serde = { version = "1.0", default-features = false, features = ["derive", "alloc"] }
