[workspace]
members = [
    # bin
    "server_crates/bin/server_bin",

    # bin for dev
    "server_crates/bin/server_dev_bin/server_api_route_builder",
    #"server_crates/bin/server_dev_bin/server_api_init",
    #"server_crates/bin/server_dev_bin/dummy_server",
    #"server_crates/bin/server_dev_bin/server_migration",

    # lib
    "sdk-common",
    "server_crates/server_api",
    "server_crates/server_api_common",
    "server_crates/worker/worker_manual",
    "server_crates/encrypted_at_rest_root"
]

[workspace.dependencies]
# server impl
hyper = { version = "0.14", features = ["full"] }
tokio = { version = "1", features = ["full"] }
tokio-util = "0.7.2"

rustgram = "0.1.8"

# dotenv vars
dotenv = "0.15.0"

# for caching trait
async-trait = "0.1.56"

rustgram-server-util = {git= "https://gitlab.com/grammm/rustgram/rustgram-server-util.git", rev = "634f8d98f99f240aa270b9f64fddd4f915e749d2", default-features = false, features = ["derive_macro"]}

#_______________________________________________________________________________________________________________________
# salt creation on server
# to get it from ssh: write this in your ~/.cargo/config.toml:
# [net]
# git-fetch-with-cli = true
sentc-crypto = {git = "ssh://git@github.com/sentclose/sentc.git", rev="722b54e4765ab7eb8eb185c6dd6a5f1826ee0005", default-features = false, features = ["rust", "server"]}

#sentc-crypto = {path = "../../sdk/crypto", default-features = false, features = ["rust", "server"]} # for local dev

#_______________________________________________________________________________________________________________________
# json handling
serde_json = {version = "1.0.81", default-features = false, features = ["alloc"]}
serde = { version = "1.0", default-features = false, features = ["derive", "alloc"] }
