[package]
name = "server_api"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# the server outputs for the frontend to handle
sentc-crypto-common = {version = "0.1.0", path = "../../sdk-common" }

# server impl
hyper = { version = "0.14", features = ["full"] }
tokio = { version = "1", features = ["full"] }
tokio-util = "0.7.2"

rustgram = "0.1.2"

# dotenv vars
dotenv = "0.15.0"

# for caching trait
async-trait = "0.1.56"

#_______________________________________________________________________________________________________________________
# to stream the input body
bytes = "1.1.0"
futures = { version = "0.3.6", default-features = false, features = ["async-await"] }

#_______________________________________________________________________________________________________________________
# json handling
serde_json = {version = "1.0.81", default-features = false, features = ["alloc"]}
serde = { version = "1.0", default-features = false, features = ["derive", "alloc"] }

#_______________________________________________________________________________________________________________________
# mysql db
mysql_async = { version = "0.30.0", optional = true }

# sqlite
deadpool-sqlite = { version= "0.4.0", optional = true }
rusqlite = { version = "0.27.0", features = ["bundled"], optional = true }

# id
uuid = {version="1.1.2", features= ["v4", "fast-rng"]}

#_______________________________________________________________________________________________________________________
# jwt handling
jsonwebtoken = { version = "8.1.1", default-features = false }
# ring crypto to crate jwt keys
ring = { version = "0.16.5", features = ["std"] }
# base64 to encode and decode the jwt key
base64 = "0.13.0"

[features]
default = ["mysql"]
mysql = ["mysql_async"]
sqlite = ["deadpool-sqlite","rusqlite"]