[package]
name = "worker_cron"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
server_api_customer = { path = "../../../server_api_customer", default-features = false }
server_api_common = { path = "../../../server_api_common", default-features = false }
server_api_file = { path = "../../../server_api_file", default-features = false }

tokio = { workspace = true }

[features]
default = ["mysql"]
mysql = ["server_api_customer/mysql", "server_api_common/mysql", "server_api_file/mysql"]
sqlite = ["server_api_customer/sqlite", "server_api_common/sqlite", "server_api_file/sqlite"]