[package]
name = "server_api_rest"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
server_api = {version = "0.1.0", path = "../../server_api", default-features = false}

tokio = { version = "1", features = ["full"] }
rustgram = "0.1.7"

[features]
default = ["server_api/default"]
mysql = ["server_api/mysql"]
sqlite = ["server_api/sqlite"]

send_mail = ["server_api/send_mail"]