[package]
name = "sentc_api_init"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
server_api_customer = {path = "../../server_api_customer", default-features = false}
server_api_common = {path = "../../server_api_common", default-features = false}

tokio = {workspace = true}

rustgram-server-util = {workspace = true}

[features]
default = ["mysql"]
mysql = ["server_api_customer/mysql","server_api_common/mysql"]
sqlite = ["server_api_customer/sqlite","server_api_common/sqlite"]