[package]
name = "server_api_all"
version = "0.1.0"
edition = "2021"
default-run = "server_api_all"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustgram = {workspace = true}
tokio = {workspace = true}

server_api_rest = {version = "0.1.0", path = "../server_api_rest", default-features = false}
server_api_file = {version = "0.1.0", path = "../server_api_file", default-features = false}
server_dashboard_backend = {version = "0.1.0", path = "../server_dashboard" }

[features]
default = ["mysql"]
mysql = ["server_api_rest/mysql","server_api_file/mysql"]
sqlite = ["server_api_rest/sqlite","server_api_file/sqlite"]

send_mail = ["server_api_rest/send_mail"]